### ISSUE TITLE
More explanation needed for calling class method on self in __init__

### ISSUE THREAD

**Issue by lantzbuilds** [learn-co-curriculum/python-p3-remembering-objects#2]
### Canvas Link

https://learning.flatironschool.com/courses/6049/pages/remembering-objects?module_item_id=439042

### Concern

Coming from Ruby, when seeing this for adding a song instance to the class `all` array:
```Python
class Song:

    all = []

    def __init__(self, name):
        self.name = name
        Song.all.append(self)
```
it makes a lot of sense, because even though __init__ is an instance method, you're referring to a class attribute, so you must use `Song.all` to access the array.  But when you refactor it to:
```Python
class Song:

    all = []

    def __init__(self, name):
        self.name = name
        self.add_song_to_all(self)

    @classmethod
    def add_song_to_all(cls, song):
        cls.all.append(song)
```
the creation of the class method makes sense so that you have a class method mutating the class attribute `all`, but the invocation `self.add_song_to_all(self)` would never work in Ruby, so it looks odd.  Here, we're taking advantage of that fact that, in Python, class attributes and methods ARE in instance scope, so that even though `self.add_song_to_all(self)` is calling a class method on an instance, Python will look for `add_song_to_all` in the class namespace when it doesn't find that method in the 'instance' namespace.
   Is this idiomatic Python, so that we eliminate all direct reference to class in `__init__`?  I would have written `Song.add_song_to_all(self)` to keep it clear that I'm calling a class method.

### Suggested Changes

add some clarification about why it's ok (or even desirable) to call a class method on `self` in `__init__`

**Comment by professor-ben** [comment]
Hi Lantz,

You are totally right here- the code works as written, but it should not be using self to call a class method.

-Ben
